'use strict';

// tests for addUser
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('addUser', '/testBuild/service/src/controller.js', 'addUser');

describe('addUser', () => {
  before((done) => {
    done();
  });

  it('Should return Ok for Valid User', async () => {
    const validUser = require(`../test-data/user.json`);
    const response = await wrapped.run(validUser);
    expect(response.statusCode).to.equal(200);
  });

  it('Should return BAD REQUEST for null body', async () => {
    const response = await wrapped.run({});
    expect(response.statusCode).to.equal(400);
  });
});
