'use strict';

// tests for getUser
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getUser', '/testBuild/service/src/controller.js', 'getUser');

describe('getUser', () => {
  before((done) => {
    done();
  });

  it('Should return more than One user', async () => {
    const response = await wrapped.run({});
    const body = JSON.parse(response.body);
    const users = JSON.parse(body.message);
    expect(users.length).to.be.greaterThan(0);
  });
});
