'use strict';

// tests for hello
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('hello', '/testBuild/service/src/controller.js', 'hello');

describe('hello', () => {
  before((done) => {
    done();
  });

  it('Response not to be empty', async () => {
    const response = await wrapped.run({});
    expect(response).to.not.be.empty;
  });

  it('Response Status to be 200', async () => {
    const response = await wrapped.run({});
    expect(response.statusCode).to.equal(200);
  });

});
