service:
  name: serverless-unit-test

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-mocha-plugin
provider:
  name: aws
  runtime: nodejs12.x

environment:
  MONGO_DB_URL: ${file(./serverless.env.${opt:stage}.yml):db.url}
  MONGO_DB_DB_NAME: ${file(./serverless.env.${opt:stage}.yml):db.name}


functions:
  hello:
    handler: src/controller.hello
    events:
      - http:
          path: /hello
          method: post
          cors: true
          private: true
  localizedHello:
    handler: src/controller.localizedHello
    events:
      - http:
          path: /localizedHello
          method: post
          cors: true
          private: true
  addUser:
    handler: src/controller.addUser
    events:
      - http:
          path: /addUser
          method: post
          cors: true
          private: true

      